### ISSUE TITLE
Youtube Music presence stops working after skipping

### ISSUE THREAD

**Issue by JustRedTTG** [PreMiD/PreMiD#867]
Steps to reproduce:
1. Install premid
2. Install the extension
3. Enable youtube music presence
4. Open https://music.youtube.com/
5. Play Mega Mix

Effects:
1. It shows on discord
2. I skip a song...
3. It freaks out
4. After a few seconds the presence is completely gone!

Versions:
1. Running Chrome extension 2.2.3
2. Running on windows 64 bit 2.2.0

NOTE: The application says it's up to date!
NOTE: I tried the installer, same version 2.2.0
NOTE: I don't know if they have to be the same version, but the extension is 2.2.3 and that's what I have :/

**Comment by dturnip** [comment]
This happens to me as well and happens because of Discord's rate limit. It's been previously addressed here in #814 :

https://github.com/PreMiD/PreMiD/issues/814#issuecomment-1126518941

**Comment by EncryptedDev** [comment]
This should have been fixed in PreMiD/Presences#6518.

If the issue persists, create an issue in PreMiD/Presences

**Comment by Hilikusz** [comment]
I'm having this very same issue right now whenever i skip a song its just gone, both extension and app is on the latest version.

**Comment by JustRedTTG** [comment]
> I'm having this very same issue right now whenever i skip a song its just gone, both extension and app is on the latest version.
> 
> 
> 
> 

I think it's because of the rate limit and they fixed it in a commit or a fork, either way it still doesn't seem to be fixed on the latest version.

**Comment by AqilCont** [comment]
I don't know if this is exactly related, but I keep seeing a completely unrelated song on my Presense even though I may have played it more than a month ago. Sometimes when I don't even have YT Music open. Is there any way to fix this?

**Comment by JustRedTTG** [comment]
> I don't know if this is exactly related, but I keep seeing a completely unrelated song on my Presense even though I may have played it more than a month ago. Sometimes when I don't even have YT Music open. Is there any way to fix this?

It is related and it's to do with discord blocking spam or something and premier isn't handling it well even when the blocking stops

**Comment by saberana** [comment]
i got the same issue

**Comment by airda2895** [comment]
I'm having the same issue. Is there any fix?

**Comment by junkiAngell** [comment]
how to fix this issue?

**Comment by andrewdevcup** [comment]
Looking at the WebSocket traffic of the extension, it does update way quicker than it should (around 6 times per second)
it should update only when pausing, resuming, changing tabs and videos.
Discord not only limits that but also stops showing the activity at all.
